title: Open Credentialing Initiative | Getting Started
description: New to the OCI? This repository gives you a high-level overview of our use-case and concepts.
show_downloads: true
theme: jekyll-theme-cayman